_commit: 0.1.7
_src_path: gh:mapp-metabolomics-unit/mapp-repo-copier-template
common_filename_pattern: '*202505131015_CVOL_*.mzML'
email: pierre-marie.allard@unifr.ch
gap_filling: false
git_repo_path: /Users/pma/git_repos/COMMONS_Lab/DBGI
github_username: digital-botanical-gardens-initiative
gnps_job_id: 4e5060d5d8204d90b5c44867b808e9d1
ionization_mode: positive
mapp_batch: mapp_batch_00174
mapp_batch_description: Untargeted metabolomics of trees from the JBUF - pos
mapp_project: mapp_project_00067
noise_level: 2000000.0
repository_name: jbuf-trees
target_variable: ATTRIBUTE_otl_organism_otol_species
recorded_setup: true
recorded_repository_name: "jbuf-trees"
recorded_author: "MAPP Metabolomics Unit"
recorder_email: "pierre-marie.allard@unifr.ch"
recorded_github_username: "digital-botanical-gardens-initiative"
recorded_mapp_project: "mapp_project_00067"
recorded_mapp_batch: "mapp_batch_00174"


